### ISSUE TITLE
Class 'IAuthenticator' has no 'providedBy' member (no-member)

### ISSUE THREAD

**Issue by mimi89999** [letsencrypt/lets-encrypt-preview#147]
In letsencrypt.scripts.main
line 95: Class 'IAuthenticator' has no 'providedBy' member (no-member)

**Comment by jdkasten** [comment]
I think the optimal solution here would be to ammend the pylintrc file to ignore these errors for the pkg_resources and zope.interface affected functions.  That way if pylint ever updates we wont have to go around removing random pylint disable statements all over the project.

I haven't looked at the pylint config file in awhile as there has been plenty of other more pressing issues in my opinion, but that is my plan.

**Comment by jdkasten** [comment]
I believe this is taken care of... Thanks @kuba!
