### ISSUE TITLE
Missing dependenices in README

### ISSUE THREAD

**Issue by JensErat** [letsencrypt/lets-encrypt-preview#151]
The README misses some dependencies. I didn't provide a pull request as this is somewhat subject for discussion. I found them missing while constructing a docker file from minimal Ubuntu for playing with.

Dependencies given:

    sudo apt-get install python python-setuptools python-virtualenv \
      python-dev gcc swig dialog libaugeas0 libssl-dev

Additionally required:

- openssl, this also should definitely be listed in a future package as requirement
- right now, git is required to fetch the code (this might be debatable)
- ca-certificates is required for communication with the ACME server, and also for fetching the code with git

None of these get installed when setting up apache2 and the already listed requirements with `apt-get install --no-install-recommends`.

**Comment by ThomasWaldmann** [comment]
@kuba said: "openssl is necessary only on the validator branch AFAIR".

Can somebody doing a fresh install please verify the dependencies again?

ca-certificates required?
openssl required?

(we won't add git as a requirement as that is only needed for developers, not once letsencrypt is released and available from pypi)

**Comment by JensErat** [comment]
OpenSSL is required by the Apache web server for TLS support.

**Comment by kuba** [comment]
oh, wow, thanks @JensErat

**Comment by jdkasten** [comment]
Apache shouldn't be required for the project.  Although it is the only thing we have implemented right now. I do believe that we will need the validator which is currently using OpenSSL so I imagine it will be included either way.

Also... https://mod.gnutls.org/

**Comment by ThomasWaldmann** [comment]
guess this can be closed, all what is for sure needed has been added.
if the validator branch is merged into master and it requires openssl, one should update the requirements then.
