### ISSUE TITLE
parsing cups printers.conf? wat?

### ISSUE THREAD

**Issue by ThomasWaldmann** [letsencrypt/lets-encrypt-preview#168]
I installed as described in the README on Ubuntu 14.04 and after starting letsencrypt from the venv, it shows the disclaimer and after I agree, it shows:

   There has been an error in parsing the file: /etc/cups/printers.conf  
   Parse error: mismatched in square lens, expecting "DefaultPrinter"   
   but got "Printer"                                                  
   No domain names were found in your installation                        
   Either specify which names you would like letsencrypt to validate    
   or add server names to your virtual hosts                         

Why is it parsing my cups printers.conf???

(the rest is ok, I have no hostnames, apache2 was freshly installed on this machine)

**Comment by jdkasten** [comment]
It is related to this...
https://github.com/letsencrypt/lets-encrypt-preview/blob/master/letsencrypt/client/augeas_configurator.py#L39

Augeas by default tries to load up everything... I know there is a way to load up only specific modules, but I haven't gotten around to it yet.

The warning statement is from here...
https://github.com/letsencrypt/lets-encrypt-preview/blob/master/letsencrypt/client/augeas_configurator.py#L45

It shouldn't affect the actual running of the program, but I am surprised that it got past the "only print out the relevant (httpd) lens filter.

The code hasn't been hit yet with review yet... I am making the rounds though and cleaning up the augeas_configurator in the "reverter branch".

If you would like to currently ignore the problem... I think it would be fine, or if you would like to investigate the Augeas module loading... that would be great!

If no one posts on this thread regarding it, I will attempt to figure it out towards the end of the "reverter" branch development.
