### ISSUE TITLE
use of pyca (cryptography.io) instead of M2Crypto

### ISSUE THREAD

**Issue by azet** [letsencrypt/lets-encrypt-preview#172]
Hi,

Just a suggestion. I've been using M2Crypto a lot, but it has flaws and there's a new project that aims to be the new 'python cryptographic authority' suitable for 2.x and 3.x: 
 - https://cryptography.io
 - https://github.com/pyca

Since there's only a few calls made to M2Crypto it might make sense to switch to `cryptography`. The code is cleaner and well maintained. Which M2Crypto isn't.

Aaron

**Comment by kuba** [comment]
Duplicate of #164

**Comment by azet** [comment]
Oh didn't see that one. Thanks. Closing.
