### ISSUE TITLE
add CLI args to override server port and scheme

### ISSUE THREAD

**Issue by frasertweedale** [letsencrypt/lets-encrypt-preview#173]
The CLI currently support overriding the server via the `--server` argument.
Please add support for overriding the port and scheme (i.e. allow plain http),
to make it easier to use letsencrypt with one's own ACME server.

**Comment by jsha** [comment]
Perhaps a better alternative: Add a --trust-root option that specifies a trust root to use when connecting to the ACME server. If you install a self-signed certificate on the ACME server, you can make a local copy of it and use that as the trust root. This would mean less difference between the code paths, I think.

**Comment by frasertweedale** [comment]
That sounds useful, but overriding the port would still be needed if server is speaking https on port `8443`, for example.

**Comment by ThomasWaldmann** [comment]
adding the port looks easy, will look into that...

**Comment by ThomasWaldmann** [comment]
https://github.com/letsencrypt/lets-encrypt-preview/pull/177

no new cli arg needed, just give -s yourserver:8443

**Comment by ThomasWaldmann** [comment]
#177 is merged, so this can be closed.
