### ISSUE TITLE
improve path / filenames for certs / keys

### ISSUE THREAD

**Issue by ThomasWaldmann** [letsencrypt/lets-encrypt-preview#179]
directories
-------------
currently it is apache2/certs/ and apache2/ssl/.

better: apache2/certs/ and apache2/keys/.

also, the directory name could be special for letsencrypt, making it e.g. apache2/le-certs and /le-keys.
this might be nice if an admin wants to keep some non-le certs/keys in the directory called certs/keys and not mix it with the le ones.

filenames
------------
currently:
key-letsencrypt_10.pem
key-letsencrypt_11.pem
key-letsencrypt_12.pem
key-letsencrypt_13.pem
key-letsencrypt_14.pem
key-letsencrypt_15.pem
key-letsencrypt_1.pem
key-letsencrypt_2.pem
key-letsencrypt_3.pem
key-letsencrypt_4.pem
key-letsencrypt_5.pem
key-letsencrypt_6.pem
key-letsencrypt_7.pem
key-letsencrypt_8.pem
key-letsencrypt_9.pem
key-letsencrypt.pem

you see: this does not even sort correctly in the directory listing.

so, the minimum fix required is to use this pattern: %04d_key-letsencrypt.pem

do you want to keep these saying-nothing filenames? we could also transform the domainname to a valid filesystem name and use that.

**Comment by jdkasten** [comment]
I agree with the special certs/keys directories and renaming.  I believe the directories should be configurable in CONFIG.py.  The file renaming should take place in the unique_file function which I believe is a part of le_util.py.

The domain name -> filesystem name won't work too well for people with multiple SANs.  (Also I imagine that most of those keys that you generated were for certificates for the same domain name).  Hopefully, people won't need to generate that many keys.

I do think we need to do a better job of communicating the key's purpose and its abilities.  Right now, every key-letsencrypt_*.pem key is technically an authorized (account) key within ACME... which will/can be different than the certificate key in the CSR.  Perhaps we should write comments in the pem files themselves about the capabilities of the key.

Example:
Authorization valid until: XXXXX
This key is an ACME authorized key for the following names: example.com, foo.example.com
(This key is not known to be contained within any Let's Encrypt certificate)????
-----BEGIN CERTIFICATE-----
....
or
Authorization valid until: XXXXX
This key is an ACME authorized key for the following names: example.com, foo.example.com
This key is used in the certificate:
Issued at: 
Issuer:
Domains: 
Original filepath: <filepath>
-----BEGIN CERTIFICATE-----
...

This allows for a bit more flexibility and gives power users more info. Thoughts?

**Comment by ThomasWaldmann** [comment]
the comment-header idea is nice, maybe use something that can be parsed easier automically. json?

this header doesn't cause any compatibility troubles?

about "not many keys" - you are offering a free and highly automatable service, so what would you expect from services which host a lot of domains and care for security? :)

**Comment by jdkasten** [comment]
Implementations should ignore things outside of the -----BEGIN CERTIFICATE--.... and ----END CERT....

> about "not many keys" - you are offering a free and highly automatable service, so what would you expect from services which host a lot of domains and care for security? :)

:) I guess I imagined people having one authorized key for many domains since this client is currently running on a single box.  I would imagine that people would want the keys that they use in CSRs/certificates to be different and separated.

> something that can be parsed easier automically. json?
I really like the json idea. :+1:

**Comment by ThomasWaldmann** [comment]
with my current code, if you give dir/basename.ext, it will generate dir/0000_basename.ext as first return value (0001... as 2nd, etc.). this sorts / looks nicely, but it never uses the basename.ext without the number prefix - is this a problem?

**Comment by jdkasten** [comment]
I personally think that is fine.

**Comment by ThomasWaldmann** [comment]
I split off the json issue to ticket #182. So this ticket shall be just about dir/filenames.

**Comment by ThomasWaldmann** [comment]
see PR #183

**Comment by jdkasten** [comment]
Thanks @ThomasWaldmann I think you solved this ticket.
