### ISSUE TITLE
ssllabs findings (sha1 sig, no hsts)

### ISSUE THREAD

**Issue by ThomasWaldmann** [letsencrypt/lets-encrypt-preview#181]
it just ran letsencrypt (did no other modifications) and let ssllabs.com grade my server configuration.

grade is "T", because the cert is just a testing cert (this is expected).
grade would be "B", if it was a real trusted cert.

Issues found:
Certificate uses a weak signature (SHA1withRSA). When renewing, ensure you upgrade to SHA2.
Guess this needs to get fixed in the ACME server.

No HSTS (yet). Needs to get fixed in the client to optionally add this to the web server config.
In the end, HSTS enables "A+" grade.

**Comment by jdkasten** [comment]
Awesome!  Thanks for investigating this @ThomasWaldmann.  We are signing our CSR's with sha256, but the server (Node-ACME) lacks sophistication.  We will be upgrading to the Boulder server once pending protocol changes happen and Boulder-> new protocol.

A few things need to happen for HSTS.  We need to adapt the client to ask about it (if it is available).  
Using this function... looking for 'http-header'  (defined in CONFIG.ENHANCEMENTS)
https://github.com/letsencrypt/lets-encrypt-preview/blob/master/letsencrypt/client/interfaces.py#L83

Come up with a nice description for it and prompt the user.

On the Installer side... (currently only Apache) we need to extend the enhance() function to handle 'http-header'... and of course put it as a supported_enhancement.

**Comment by jdkasten** [comment]
Since this is completely based on server issues and HSTS will be a policy decision on the server for installers that are capable.  I think this issue can be closed.
