### ISSUE TITLE
py26 lint fails

### ISSUE THREAD

**Issue by kuba** [letsencrypt/lets-encrypt-preview#187]
astroid-1.3.4 seems to be incompatible with python 2.6 (c.f. #97):

```
  File "/home/travis/build/letsencrypt/lets-encrypt-preview/.tox/lint/lib/python2.6/site-packages/astroid-1.3.4-py2.6.egg/astroid/modutils.py", line 69
    get_python_lib(standard_lib=True, prefix=sys.prefix),
                                                        ^
SyntaxError: invalid syntax
ERROR: InvocationError: '/home/travis/build/letsencrypt/lets-encrypt-preview/.tox/lint/bin/pylint --rcfile=.pylintrc letsencrypt'
___________________________________ summary ____________________________________
ERROR:   lint: commands failed
```

https://travis-ci.org/letsencrypt/lets-encrypt-preview/jobs/48161759#L1633

**Comment by kuba** [comment]
Also, https://pypi.python.org/pypi/astroid/1.3.0 -> `astroid is compatible with Python 2.7 as well as 3.3 and later. astroid uses the same code base for both Python versions, using six.`

**Comment by ThomasWaldmann** [comment]
upstream bug: https://bitbucket.org/logilab/astroid/issue/76/python26-compatibility

**Comment by kuba** [comment]
Upstream fixed. I guess it'll be available in (yet unreleased) 1.3.5.

**Comment by ThomasWaldmann** [comment]
do we want to keep this open regarding that PR #206 was merged?

we could just document "run pylint with python 2.7 please".

**Comment by kuba** [comment]
It's more or less documented at https://github.com/letsencrypt/lets-encrypt-preview/blob/master/tox.ini#L20. @jdkasten, please close :)
