### ISSUE TITLE
docs creation / reorganize

### ISSUE THREAD

**Issue by ThomasWaldmann** [letsencrypt/lets-encrypt-preview#194]
there are some docs on readthedocs, but currently only API docs, so non-developers looking there might be a bit disappointed.

my suggestion (and also I am offering to do it) is to move most of the README into the docs and only keep introductory information in the README.

About documentation structure: I have thought through and optimized this for one of my other projects and would suggest to do it in a similar way to avoid redundancies, see http://nsupdateinfo.readthedocs.org/en/latest/intro.html and https://raw.githubusercontent.com/nsupdate-info/nsupdate.info/master/docs/intro.rst - you see that introduction chapter of the docs is just the README and the CHANGES from the toplevel dir included there.

What do you think?

**Comment by kuba** [comment]
I like it. Can we also have the same badges? :)

**Comment by ThomasWaldmann** [comment]
OK, I'll work on it. The pypi and downloads badge only makes sense after first pypi release, but the coverage badge might work now.

**Comment by ThomasWaldmann** [comment]
see PR #196

**Comment by ThomasWaldmann** [comment]
hmm, I just visited coveralls.io and they seem to want r/w access to repositories now. :-(
so, maybe rather no coveralls.io badge due to invasive permission demand.

**Comment by ThomasWaldmann** [comment]
PR was merged, please close.
