### ISSUE TITLE
Subsequent tox invocations fail immediately

### ISSUE THREAD

**Issue by schoen** [letsencrypt/lets-encrypt-preview#235]
On my system (Ubuntu 14.04), initial invocation of tox (in a virtualenv, after python setup.py install) works successfully, but all subsequent invocations fail immediately with

    AssertionError: Egg-link /home/schoen/src/lets-encrypt-preview does not match installed location of letsencrypt (at /home/schoen/src/lets-encrypt-preview/.tox/lint/lib/python2.7/site-packages)

However, removing the entire letsencrypt/.tox directory will get rid of this error (at the cost of having to rebuild *all* of the packages that tox brings in), but then running tox a second time brings the error message back.

**Comment by kuba** [comment]
I have bisected Travis build logs. Problem occurs somewhere between builds [227](https://travis-ci.org/letsencrypt/lets-encrypt-preview/jobs/48240448) and [266](https://travis-ci.org/letsencrypt/lets-encrypt-preview/jobs/48749120).

Note that #206 was introduced in between (build [257](https://travis-ci.org/letsencrypt/lets-encrypt-preview/builds/48686937)), but I don't think build matrix is the problem itself. #206 also changed setup.py to use `pylint>=1.4.0`, but, again, I don't feel its the direct cause either. Presented below is the diff between installed package versions based on the logs, [227](https://s3.amazonaws.com/archive.travis-ci.org/jobs/48240448/log.txt) on the left and [266](https://s3.amazonaws.com/archive.travis-ci.org/jobs/48749120/log.txt) on the right.

```diff
2,3c2,3
< astroid==1.2.1
< coverage==4.0a3
---
> astroid==1.3.4
> coverage==4.0a4
13c13
< pylint==1.3.1
---
> pylint==1.4.1
17c17
< setuptools==11.0
---
> setuptools==12.0.5
21c21
< virtualenv==12.0.5
---
> virtualenv==12.0.6
```

My bet is that `tox` doesn't like to be run under virtualenv with `setuptools==12.0.5` and `virtualenv==12.0.6`...

@schoen Could you, please, try the following (with #234 applied beforehand!):
```bash
rm -rf venv .tox
virtualenv --no-site-packages venv
./venv/bin/python setup.py easy_install letsencrypt[testing]
```
1. Now run `./venv/bin/tox -e py27` multiple times. Does it work?
2. If above works, run `./venv/bin/tox` multiple times. Does it work?

**Comment by kuba** [comment]
It's actually `pip==6.0.7` that's broken... quickfix: `./.tox/py27/bin/pip install --upgrade pip=6.0.6`

**Comment by kuba** [comment]
I hope #237 resolves this correctly now. @schoen, would you be so kind to try the patch? :)

**Comment by schoen** [comment]
Hi @kuba, #237 did fix this for me!  Thanks for figuring it out.
