### ISSUE TITLE
Consider using fuser instead of netstat for already_listening

### ISSUE THREAD

**Issue by schoen** [letsencrypt/lets-encrypt-preview#245]
It could be easier and cleaner to parse, and might potentially be more portable to other operating systems.

**Comment by jsha** [comment]
I looked briefly into this, and it looked like fuser doesn't detect listeners running as different users, unless its running as root. Netstat appears to be able to show listeners even when running as non-root.

**Comment by kuba** [comment]
Rather than parsing, could we, please, use some Python library for that?

**Comment by schoen** [comment]
I will try to convert it to use psutil, which has comparable functionality.

**Comment by schoen** [comment]
PR #249 should fix this (using the Python library psutil instead of parsing netstat output).
