### ISSUE TITLE
coveralls duplicate comments

### ISSUE THREAD

**Issue by kuba** [letsencrypt/lets-encrypt-preview#253]
coveralls sends two duplicate comments, e.g.:
- https://github.com/letsencrypt/lets-encrypt-preview/pull/252#issuecomment-75245797
- https://github.com/letsencrypt/lets-encrypt-preview/pull/252#issuecomment-75245802

I guess it's a matter of configuration. Otherwise we should report upstream.

**Comment by kuba** [comment]
More interesting example (two comments are different):
- https://github.com/letsencrypt/lets-encrypt-preview/pull/251#issuecomment-75237272 ("Coverage decreased (-83.34%) to 0.0% when pulling b8ba6fe on scottjbarr:master into 5ab9b7c on letsencrypt:master."
- https://github.com/letsencrypt/lets-encrypt-preview/pull/251#issuecomment-75237273 "Coverage remained the same at 83.34% when pulling b8ba6fe on scottjbarr:master into 5ab9b7c on letsencrypt:master."

I cannot see anything strange in the corresponding https://coveralls.io/builds/1963241...

**Comment by kuba** [comment]
Another case, when there are actually no duplicates at all: #249!

I honestly cannot spot a pattern, but smells like upstream.. :( Does coveralls.io provide any admin panel you have access to, @jdkasten? Could you have a look?

**Comment by jcjones** [comment]
Taking Job 449 at Travis, all four sub-jobs send data to Coveralls. That actually could produce four comments! Basically, 

[Job 449.1](https://travis-ci.org/letsencrypt/lets-encrypt-preview/jobs/51498447)
[Job 449.2](https://travis-ci.org/letsencrypt/lets-encrypt-preview/jobs/51498448)
[Job 449.3](https://travis-ci.org/letsencrypt/lets-encrypt-preview/jobs/51498449)
[Job 449.4](https://travis-ci.org/letsencrypt/lets-encrypt-preview/jobs/51498450)

When I was having this problem on boulder, I took the easy way out and reduced the build to a single job. In your case, given how travis and tox are interacting, I think you want to tell travis to only call coveralls when TOXENE=cover .

Or maybe it's a stale workdir problem and you should clear the cover data after calling coveralls?

**Comment by jdkasten** [comment]
Unfortunately, I do not have access to any panel. I know where it should be...
https://coveralls.zendesk.com/hc/en-us/articles/201774895-Notifications

**Comment by jcjones** [comment]
While I set up coveralls for this repo, I too do not have that button.

Anyway, the coveralls workflow is very simple: it will write a comment each time `coveralls` has files on disk. I'll try a quick patch to fix it.

**Comment by kuba** [comment]
This has been fixed in #264.
