### ISSUE TITLE
letsencrypt ubuntu installation

### ISSUE THREAD

**Issue by sp-admin** [letsencrypt/lets-encrypt-preview#258]
following the how-to described in http://letsencrypt.readthedocs.org/en/latest/using.html i have this error at the second step:

gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -c _configtest.c -o _configtest.o
success!
removing: _configtest.c _configtest.o
c/_cffi_backend.c:13:17: fatal error: ffi.h: No such file or directory
compilation terminated.
error: Setup script exited with error: command 'gcc' failed with exit status 1

**Comment by sp-admin** [comment]
fixed installing also libffi-dev package with apt

**Comment by kuba** [comment]
Thanks for the heads. `libffi-dev` has been already added to the documentation as necessary dependency in  e399f7927f0ce7ea2eaa3fc2542820cdfb341aeb. Although automatic ReadTheDocs build has been triggered, it has failed. I'll look into that problem soon.

**Comment by kuba** [comment]
Reported in #259
