### ISSUE TITLE
help doesn't work

### ISSUE THREAD

**Issue by sp-admin** [letsencrypt/lets-encrypt-preview#260]
# letsencrypt --help
Traceback (most recent call last):
  File "/usr/local/bin/letsencrypt", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2707, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: PyOpenSSL

**Comment by sp-admin** [comment]
to use the help it's necessary declare all the path where letsencrypt is installed originally:

/usr/local/letsencrypt# ./venv/bin/letsencrypt /usr/local/bin/letsencrypt
usage: letsencrypt [-h] [-d DOMAIN [DOMAIN ...]] [-s SERVER] [-p PRIVKEY]
                   [-B N] [-k] [-b N] [-v] [-r] [-e] [-t]
                   [--config-dir CONFIG_DIR] [--work-dir WORK_DIR]
                   [--backup-dir BACKUP_DIR] [--key-dir KEY_DIR]
                   [--cert-dir CERT_DIR] [--le-vhost-ext LE_VHOST_EXT]
                   [--cert-path CERT_PATH] [--chain-path CHAIN_PATH]
                   [--apache-server-root APACHE_SERVER_ROOT]
                   [--apache-mod-ssl-conf APACHE_MOD_SSL_CONF]
                   [--apache-ctl APACHE_CTL] [--apache-enmod APACHE_ENMOD]
                   [--apache-init-script APACHE_INIT_SCRIPT]
                   [-c FILE [FILE ...]] [--export-conf-file [FILE]]

**Comment by kuba** [comment]
Could you please paste the exact command and whole traceback you got in your first attempt together with your current working directory (run `pwd`)? It seems to me that you might have attempted to install the project using `sudo pip install` instead of installing to the virtualenv, or you skipped `source venv/bin/activate` step.

**Comment by sp-admin** [comment]
root@:~# pwd
/root
root@:~# letsencrypt --help
Traceback (most recent call last):
  File "/usr/local/bin/letsencrypt", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2707, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: PyOpenSSL

for the virtualenv i used the wiki process, so without "source venv/bin/activate" step. i run the comand and actually now it works:

root@:~# letsencrypt --help
usage: letsencrypt [-h] [-d DOMAIN [DOMAIN ...]] [-s SERVER] [-p PRIVKEY]
                   [-B N] [-k] [-b N] [-v] [-r] [-e] [-t]
                   [--config-dir CONFIG_DIR] [--work-dir WORK_DIR]
                   [--backup-dir BACKUP_DIR] [--key-dir KEY_DIR]
                   [--cert-dir CERT_DIR] [--le-vhost-ext LE_VHOST_EXT]
                   [--cert-path CERT_PATH] [--chain-path CHAIN_PATH]
                   [--apache-server-root APACHE_SERVER_ROOT]
                   [--apache-mod-ssl-conf APACHE_MOD_SSL_CONF]
                   [--apache-ctl APACHE_CTL] [--apache-enmod APACHE_ENMOD]
                   [--apache-init-script APACHE_INIT_SCRIPT]
                   [-c FILE [FILE ...]] [--export-conf-file [FILE]]

letsencrypt client 0.1

optional arguments:
  -h, --help            show this help message and exit
  -d DOMAIN [DOMAIN ...], --domains DOMAIN [DOMAIN ...]
  -s SERVER, --server SERVER
                        CA hostname (and optionally :port). The server
                        certificate must be trusted in order to avoid further
                        modifications to the client.
  -p PRIVKEY, --privkey PRIVKEY
                        Path to the private key file for certificate
                        generation.
  -B N, --rsa-key-size N
                        Size of the RSA key.
  -k, --revoke          Revoke a certificate.
  -b N, --rollback N    Revert configuration N number of checkpoints.
  -v, --view-config-changes
                        View checkpoints and associated configuration changes.
  -r, --redirect        Automatically redirect all HTTP traffic to HTTPS for
                        the newly authenticated vhost.
  -e, --agree-tos       Skip the end user license agreement screen.
  -t, --text            Use the text output instead of the curses UI.
  --config-dir CONFIG_DIR
                        Configuration directory.
  --work-dir WORK_DIR   Working directory.
  --backup-dir BACKUP_DIR
                        Configuration backups directory.
  --key-dir KEY_DIR     Keys storage.
  --cert-dir CERT_DIR   Certificates storage.
  --le-vhost-ext LE_VHOST_EXT
                        SSL vhost configuration extension.
  --cert-path CERT_PATH
                        Let's Encrypt certificate file.
  --chain-path CHAIN_PATH
                        Let's Encrypt chain file.
  --apache-server-root APACHE_SERVER_ROOT
                        Apache server root directory.
  --apache-mod-ssl-conf APACHE_MOD_SSL_CONF
                        Contains standard Apache SSL directives.
  --apache-ctl APACHE_CTL
                        Path to the 'apache2ctl' binary, used for 'configtest'
                        and retrieving Apache2 version number.
  --apache-enmod APACHE_ENMOD
                        Path to the Apache 'a2enmod' binary.
  --apache-init-script APACHE_INIT_SCRIPT
                        Path to the Apache init script (used for server
                        reload/restart).

configuration file options:
  -c FILE [FILE ...], --conf-file FILE [FILE ...]
                        specify config files
  --export-conf-file [FILE]
                        translate arguments into a config file

**Comment by kuba** [comment]
Thanks for feedback! There are a couple of things that went wrong in here, so bear with me for a moment.

1. You should not run any of the commands while being logged in as root, unless you really know what you're doing!

2. My bad, there is no info about `source venv/bin/activate` in the docs. Sorry for confusion!

3. Docs say first about `sudo ./venv/bin/letsencrypt` then about `letsencrypt --help`, which should, indeed, read `./venv/bin/letsencrypt --help` instead. Could you please reopen this bug to allow us to keep track of the fix progress?

4. Should you have followed the instructions carefully, you would not be able to run just `letsencrypt` (without specifying the path to the binary). You must have had run `python setup.py install` (as root!) by mistake, which in turn installed letsencrypt system-wide... Depending on what do you keep on your (hopefully testing) machine, and who can log in, this might be quite undesirable from the security point of view, since the project is still in deep alpha!

**Comment by sp-admin** [comment]
yeah it's just a test machine because i'm interested to be an active part in this amazing project! i'm opening again the bug ticket
