### ISSUE TITLE
Is there a standard version of Ubuntu for letsencrypt build on ?

### ISSUE THREAD

**Issue by AaronNGray** [letsencrypt/lets-encrypt-preview#265]
Hi,

Is there a standard version of Ubuntu that letsencrypt builds on ?
Can people tag off below on versions that its been built and tested on and wether there are any problems on particular versions of Ubuntu, Server, 32/64 bit etc, ....

Many thanks in advance

**Comment by ThomasWaldmann** [comment]
A while ago I tried the code on Ubuntu 14.04 64bit Desktop and it worked.
I don't think that there should be an issue on other 14.04 flavours.

**Comment by jdkasten** [comment]
Ubuntu 14.04.2 LTS 64 bit server is certainly the version that is tested the best.

I did just install/run it on Ubuntu 12.04.5 LTS 64bit Server and it appears to work there also.
