### ISSUE TITLE
Is anyone working on a Fedora port ?

### ISSUE THREAD

**Issue by AaronNGray** [letsencrypt/lets-encrypt-preview#266]
Is anyone working on a Fedora port ?

**Comment by kuba** [comment]
Duplicate of #15. Please use search.

**Comment by AaronNGray** [comment]
Looks like it builds properly on Fedora. I built it last night on my main server and noticed the word "error" flashing by but they were not errors, so erroniously thought there were errors despite the "success !" message. Theres quite a few warning though, but they look safe.

Documented here :-

    https://github.com/AaronNGray/lets-encrypt-preview/blob/fedora/debug/out
