### ISSUE TITLE
Fedora Warnings

### ISSUE THREAD

**Issue by AaronNGray** [letsencrypt/lets-encrypt-preview#268]
Fedora build Warning listed here :-

https://github.com/AaronNGray/lets-encrypt-preview/blob/fedora/debug/warnings

**Comment by kuba** [comment]
The only warning that comes from our project relates to https://github.com/letsencrypt/lets-encrypt-preview/blob/master/MANIFEST.in#L3, namely that we do not include `*.sh` files any more. Would you like to send a PR that deletes this line? Otherwise, it looks harmless, comparable output can be found on Debian/Ubuntu... (have a look at travis build logs for comparison)

**Comment by AaronNGray** [comment]
I had not built on Ubuntu so was not aware of this. 
I am not familiar enought with the project code but I agree with you the warnings look harmless. But theres a lot of SWIG warnings of uninitialized variables, which should ideally be cleared up if possible.

**Comment by kuba** [comment]
Unfortunately this is not only unrelated to our code (as I said, the only warning that originates from this project is the aforementioned line), but also WONTFIX in general, unless you manage to persuade upstream (M2Crypto) to accept patches for those SWIG warnings...

**Comment by schoen** [comment]
We would also like to migrate away from M2Crypto if we can get a Python crypto library that does everything. M2Crypto now appears largely unmaintained, and we unfortunately have dependencies on several different Python crypto bindings for different purposes.

Issue #164 tracks this.

**Comment by AaronNGray** [comment]
Why not just lift the code out of SWIG ?

**Comment by schoen** [comment]
Additional maintenance work at a low layer that we hope will be replaced entirely, I suppose.

I agree it's an option as a last resort; @jdkasten did some SWIG work successfully on an earlier version of this project to expose some OpenSSL functions that M2Crypto didn't. But it seems a lot easier for maintenance and testing purposes to have everything in our project, at least, be at the Python level.

**Comment by AaronNGray** [comment]
Might be an idea to do away with venv and port code to Python 3 at the same
time. Also are there any licensing issues ?
