### ISSUE TITLE
Ubuntu 14.10 x64 - Error: Unable to find 'openssl/opensslconf.h'; Build Fails (using directions)

### ISSUE THREAD

**Issue by pavgup** [letsencrypt/lets-encrypt-preview#276]
Using the installation notes on https://letsencrypt.readthedocs.org/en/latest/using.html#installation, I attempted to give letsencrypt a whirl on a fresh Ubuntu 14.10 x64 digitalocean droplet.  For some weird reason (and I repeated this more than once), when you use the virtualenv commands to get everything going, there are failures in pulling in the right includes -- in particular, the m2crypto package dies while trying to use swig.  Here's what I ran:
  ```
  virtualenv --no-site-packages -p python2 venv
  ./venv/bin/python setup.py install
  sudo ./venv/bin/letsencrypt
  ```
Running that, you always end up with the build failing when swig takes over -- I've abbreviated the logs a tidbit here, but this is what you see:
  ```
  copying M2Crypto/SSL/ssl_dispatcher.py -> build/lib.linux-x86_64-2.7/M2Crypto/SSL
  copying M2Crypto/SSL/Connection.py -> build/lib.linux-x86_64-2.7/M2Crypto/SSL
  copying M2Crypto/SSL/cb.py -> build/lib.linux-x86_64-2.7/M2Crypto/SSL
  copying M2Crypto/SSL/Checker.py -> build/lib.linux-x86_64-2.7/M2Crypto/SSL
  copying M2Crypto/SSL/timeout.py -> build/lib.linux-x86_64-2.7/M2Crypto/SSL
  running build_ext
  building 'M2Crypto.__m2crypto' extension
  swigging SWIG/_m2crypto.i to SWIG/_m2crypto_wrap.c
  swig -python -I/usr/include/python2.7 -I/usr/include -I/usr/include/openssl -includeall -modern -o   SWIG/_m2crypto_wrap.c SWIG/_m2crypto.i
  SWIG/_evp.i:12: Error: Unable to find 'openssl/opensslconf.h'
  SWIG/_ec.i:7: Error: Unable to find 'openssl/opensslconf.h'
  error: command 'swig' failed with exit status 1
  ```
The file that swig (which has both a 3.x and 2.x branch in the repo -- might be valuable to be explicit about this need) is looking for is located in /usr/include/x86_64-linux-gnu/openssl/opensslconf.h, but there is no effective include to find that header.  Seeing that it was struggling to find that file, I ended up stumbling into a discussion about the libssl-dev package (under the larger openssl package) that is important for the deb/ubuntu folks: http://askubuntu.com/questions/523831/opensslconf-h-not-found/594486#594486.  In the end, I put in a bit of effort, but it certainly seemed like a problem with the m2crypto or virtualenv setups.  And here's what cements it for me -- I was able to comfortably come up with two working solutions to keep things chugging along.

1. Use the ubuntu-supplied m2crypto package (inside the cloned letsencrypt directory, of course) to avoid having to compile the package (meh.):

  ```
  sudo apt-get install -y python-m2crypto
  virtualenv --system-site-packages -p python2 venv
  ./venv/bin/python setup.py install
  ```

2. I then gave pip a shot at running the installation and that seemed to go a lot more smoothly.  To be clear, I didn't use any of the virtualenv commands (:(), and essentially ran (again inside the cloned letsencrypt directory):

  ```
  sudo apt-get install -y python-pip
  pip install -e .
  ```

I have a sneaking suspicion these directions: https://letsencrypt.readthedocs.org/en/latest/using.html#installation could use a once over.

**Comment by kuba** [comment]
From the referenced issue in martinpaljak/M2Crypto#62, it seems like `apt-get install dpkg-dev` fixes it?

**Comment by pavgup** [comment]
Sorry, my fault.  I should have looped back here. For the moment, the dpkg-dev solution gives M2Crypto a blunt hack to paper over a break in multiarch detection. Really dpkg-dev exists for debian package developers, not for it's normal utilities. Either way, it feels unhealthy for projects feeling the downstream effects of the martinpaljak/M2Crypto#62 to advocate for that dpkg-dev solution.

In #281, I'm essentially plopping dpkg-dev into a build strategy when using virtualenv and apt to answer dependencies to get things going, but the strategy using pip doesn't create this requirement.  And in #281, my thinking is that the virtualenv+apt build strategy might just not be great and depending on pip might be an alternative strategy.  Frankly, you might control for the environments that this works in more directly with some pip requirements.

And just to make it clear that I'm long-winded: If I'm reading #164 correctly, the intention is to move away from m2crypto anyway. I think this issue dies as the marker on the roadmap is pushed forward. So.. that's good.  :-)

I think #281 (where the dpk-dev piece is bluntly dropped in), or the decision to use pip requirements, or, eventually, the answer from #164 could close this.

**Comment by schoen** [comment]
It isn't clear that we'll actually be able to get away from M2Crypto prior to the wide launch of this package, unfortunately. We are hoping to be issuing certs to the public and have people deploying them this summer -- and I'm not sure that we'll have a reasonable replacement available by then!

**Comment by mcepl** [comment]
> Since upstream M2Crypto is very unlikely to fix it anytime soon,

Could you please explain to me what’s wrong with M2Crypto? I am trying to revive the upstream of the project at https://gitlab.com/m2crypto/m2crypto/ so you can file a issue there.

**Comment by ReturnHere** [comment]
sudo apt-get install python-m2crypto

**Comment by mcepl** [comment]
> sudo apt-get install python-m2crypto

@ReturnHere  Could you elaborate a little bit? It means it has been fixed in Debian, or it is broken there, or what? (hint: I don't use a Debian-based distro).

**Comment by imreACTmd** [comment]
Latest ubuntu libssl-dev moved opensslconf.h from /usr/include/openssl to /usr/include/x86_64-linux-gnu/openssl/.

**Comment by mcepl** [comment]
It's https://gitlab.com/m2crypto/m2crypto/issues/69 now.

**Comment by ReturnHere** [comment]
I just fixed it in debian system

2015-10-19 16:23 GMT+08:00 Matěj Cepl <notifications@github.com>:

**Comment by zirou30** [comment]
Thank you @ReturnHere  this command fix my problem in ubuntu 15.10

**Comment by benhosmer** [comment]
In CentOS, RHEL, Fedora etc:

`yum -y install openssl-devel`

**Comment by pavgup** [comment]
Fantastic
