### ISSUE TITLE
Ubuntu 14.04: setting up dev environment  fails on: unable to execute "swig"

### ISSUE THREAD

**Issue by tchalvak** [letsencrypt/lets-encrypt-preview#283]
What follows is the output, followed by ubuntu kernel and version info.
$ sudo python setup.py dev

running develop
running egg_info
writing requirements to letsencrypt.egg-info/requires.txt
writing letsencrypt.egg-info/PKG-INFO
writing top-level names to letsencrypt.egg-info/top_level.txt
writing dependency_links to letsencrypt.egg-info/dependency_links.txt
writing entry points to letsencrypt.egg-info/entry_points.txt
reading manifest file 'letsencrypt.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'letsencrypt.egg-info/SOURCES.txt'
running build_ext
Creating /usr/local/lib/python2.7/dist-packages/letsencrypt.egg-link (link to .)
Removing letsencrypt 0.1 from easy-install.pth file
Adding letsencrypt 0.1 to easy-install.pth file
Installing letsencrypt script to /usr/local/bin

Installed /home/kzqai/src/lets-encrypt-preview
Processing dependencies for letsencrypt==0.1
Searching for M2Crypto
Reading https://pypi.python.org/simple/M2Crypto/
Best match: M2Crypto 0.22.3
Downloading https://pypi.python.org/packages/source/M/M2Crypto/M2Crypto-0.22.3.tar.gz#md5=573f21aaac7d5c9549798e72ffcefedd
Processing M2Crypto-0.22.3.tar.gz
Writing /tmp/easy_install-CkvyTM/M2Crypto-0.22.3/setup.cfg
Running M2Crypto-0.22.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-CkvyTM/M2Crypto-0.22.3/egg-dist-tmp-awcdKE
unable to execute 'swig': No such file or directory
error: Setup script exited with error: command 'swig' failed with exit status 1

$ version
Linux version 3.13.0-46-generic (buildd@tipua) (gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) ) #77-Ubuntu SMP Mon Mar 2 18:23:39 UTC 2015
Ubuntu 14.04.2 LTS \n \l

Linux hal3k 3.13.0-46-generic #77-Ubuntu SMP Mon Mar 2 18:23:39 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
cat /proc/version
cat /etc/issue
uname -a

**Comment by kuba** [comment]
Please follow installation instructions at http://letsencrypt.readthedocs.org/en/latest/using.html.

**Comment by kuba** [comment]
If you managed to get it working @tchalvak, please close this bug, thanks! :)

**Comment by tchalvak** [comment]
Nope, didn't but can just close.
