### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by kuba** [letsencrypt/lets-encrypt-preview#284]
@jdkasten, we should set up a FAQ list ASAP, as some questions notoriously keep coming back.

1. Do you support wildcard certificates? Multidomain?
2. Why does the client require root?
3. Launch time?
4. Are Letsencrypt certificates recognized by modern browsers and operating systems? How is IdenTrust related?
5. Target audience? (Individuals, companies?)

Some of them are not much related to the client implementation, but it's mostly us hanging around in #letsencrypt who have to answer...

I'd personally put it in docs/faq.rst rather than GitHub wiki.

**Comment by jdkasten** [comment]
Just an update... there is a FAQ PR currently being discussed for the main website.

**Comment by edgluk** [comment]
1. Let's encrypt (LE) will only be a broker for other certificate authorities? (RapidSSL, Verisign, Comodo etc.?) And that means that not all certificates will be free?
2. FAQ should contain information, that LE will do only domain validation (eg. no green bar at browser), but not extended validation (EV). At least for now.
3. Domain validation will be done by DVSNI and DNS challenge.
4. What will happen to RapidSSL, Verisign, Comodo and other certificate sellers? Will they try to spread an idea that domain validates certificates are not good enough and start selling EV certs or what?

**Comment by j15e** [comment]
I guess the website PR you are talking about is private? @jdkasten

**Comment by edgluk** [comment]
Could be. It’s just a rumour I heard at IRC channel :)

**Comment by jdkasten** [comment]
@j15e Yes, the website PR is in a private repo. 

@edgluk Let's Encrypt will not be a certificate reseller or broker for other CAs.  It will be its own CA and will be cross-signed by Identrust at launch.  (Granting full browser compatibility from the start)  All certificates signed by Let's Encrypt will be free.

**Comment by kuba** [comment]
General project FAQ exists now at https://letsencrypt.org/faq! :)

It doesn't address multidomain (SAN) or target audience, where the former is really frequent question (ping @bdaehlie), but I'll close this issue for now.
