### ISSUE TITLE
Bootstrap scripts

### ISSUE THREAD

**Issue by kuba** [letsencrypt/lets-encrypt-preview#302]
In order to be more DRY (reduce maintenance burden), how about a `bootstrap/ubuntu/trusty.sh` script with all necessary `apt-get`s? We would call it from `travis.yml`, from `Dockerfile` (#297) and tell people to use it for installation in `using.rst`.

Obviously, we could have similar bootstrap scripts for other platforms.

(copied from https://github.com/letsencrypt/lets-encrypt-preview/pull/297#discussion_r26876873)

**Comment by garrettr** [comment]
@kuba This could be easily adapted from the `$ubuntu_setup_script` in Vagrantfile.
