### ISSUE TITLE
Don't configure Apache or other thing, just gimme SSL certificate

### ISSUE THREAD

**Issue by psandoval** [letsencrypt/lets-encrypt-preview#339]
letsencrypt --update --fqdn some.domain.com --no-config

"--no-config"
Just update cert file, don't configure server config.

---
And what about Windows? (For example, IIS) Can I get "letsencrypt.exe" CLI app?

**Comment by schoen** [comment]
Hi,

Please see prior issues #232 (getting a cert and saving it without installing it into a server) and #116, #288 (Windows support). As a summary, the standalone authenticator is already working and is able to get certs without configuring a server. We're still waiting for an upcoming meeting to discuss Windows client support.

**Comment by jdkasten** [comment]
Also, please see #285 and #136 for the future of the CLI.
