### ISSUE TITLE
What kind of cert do you offer?

### ISSUE THREAD

**Issue by fr330n1y** [letsencrypt/lets-encrypt-preview#342]
Does this project offers FREE

1. EV SSL certificate
2. Wildcard domain certificate

?

**Comment by schoen** [comment]
No, neither of these will be available from Let's Encrypt when we launch.

EV certs require human intervention and research that can't be automated, so we can't issue them in an automated fashion. Right now, the Let's Encrypt CA plans to provide DV certs in a completely automated manner.

The Let's Encrypt CA won't support wildcard certificates at launch, but could consider them in the future. You can see issue #66 for more discussion about this.
