### ISSUE TITLE
Support the domain 3 levels srv.example.com and etc. 

### ISSUE THREAD

**Issue by k0rbendallas** [letsencrypt/lets-encrypt-preview#355]
I have not found documentation about domains server.example.com.
Can I use the service for a domain mail.server.example.com?
I administer domain level 4 and I want to get my mail server worked through ssl.
Possible?

**Comment by diracdeltas** [comment]
Yes, the Let's Encrypt configurator should work for arbitrarily deep subdomains. (However, there is currently no support for SMTP; see #53)

**Comment by jdkasten** [comment]
As a follow up... if you implement the [IInstaller interface](https://github.com/letsencrypt/lets-encrypt-preview/blob/master/letsencrypt/client/interfaces.py#L141) and use the Standalone Authenticator.  It would be possible to automate the retrieval and installation of the certificate for mail servers.
