### ISSUE TITLE
API docs missing for nginx plugin

### ISSUE THREAD

**Issue by kuba** [letsencrypt/lets-encrypt-preview#356]
API docs for nginx plugin should be found at https://github.com/letsencrypt/lets-encrypt-preview/tree/master/docs/api/client/plugins

**Comment by diracdeltas** [comment]
I was worried that docs would mislead developers into thinking that the nginx plugin actually works on nginx right now (it won't until DVSNI support is added, hopefully soon). I can add them if that's not an issue.

**Comment by kuba** [comment]
I actually got confused myself by having nginx plugin merged with `master` already (it should probably go to nginx branch until its working)... Nevertheless, since #351 has been already pulled it, this bug is just a reminder to include the docs at some point. We could leave it until later, but it probably would be best to include it now with a `.. warning:: This plugin is a stub, does not support DVSNI yet!` :)
