### ISSUE TITLE
Simple question... will you support crappy hosting companies?

### ISSUE THREAD

**Issue by joquk** [letsencrypt/lets-encrypt-preview#373]
So, Freeola... GoDaddy... all those hosting companies host websites for millions of people.

But often, they do not offer SSH access to the actual servers themselves. Or if they do - they ban installation of software (Gandi Simple hosting does this)

Its great for people with their own web servers on AWS to sudo apt-get and lets-encrypt but for users of the provided hosting companies, will you provide a solution for them? Otherwise how will you ever manage to get 100% of the web encrypted! Millions of those sites exist...

My initial thoughts are

- DNS based validation
- Ability to use above to generate certs on local PC using lets-encrypt and then upload to hosting company who accepts cert files
- Maybe even some say a web client on your website to use DNS validation for users who are not comfortable with command line?

I can't wait for your product myself as it seems I am the target audience (bunch of client websites all on servers I 100% control) --- but I do feel for the smaller companies and individuals who pay for managed hosting and cannot get full server control but do have full domain control and ability to upload certs to their provider.

I'm just keen to know if you intent to help this use case?

**Comment by joquk** [comment]
(Also worst case would this work.... user sets domains DNS to a friends server who does have full control, friend sorts out free SSL certs using lets-encrypt as usual, friend exports cert files out of lets-encrypt, send cert files to user, user uploads the certs to hosting company and changes DNS a second time to point it back at crappy hosting ---- unless you somehow block access to the created certs, this would work? Would be silly though as users website goes up and down once a year when a renewal is required...)

**Comment by schoen** [comment]
Hi @joquk, we've been talking to some hosting companies about integrating Let's Encrypt. I hope lots of them will be interested in providing our certs for their users; we're happy to work with them to help make that happen. You can also do the thing you suggest in your second comment -- getting certs on a separate machine and them copying them onto your server.

**Comment by joquk** [comment]
Thanks for the response.
I also very much hope hosting providers get involved... but when so many of them make a fortune selling their own SSL certificates, I won't hold my breath waiting for them to embrace the future any time soon.
I really wish you guys the best of luck!

**Comment by pascalwacker** [comment]
In Switzerland 2 of the bigger hosting provider (Hostpoint and Cyon) already offer letsencrypt certificates, so there's hope (:
