### ISSUE TITLE
I/O possible

### ISSUE THREAD

**Issue by kuba** [letsencrypt/lets-encrypt-preview#378]
I often (but not always) get the `I/O possible` error. It's been happening for a while now, long before boulder branch got included.
```
DEBUG:root:Sending POST data: {"header": {"alg": "RS256", "jwk": {"e": "AQAB", "kty": "RSA", "n": "rkxqHTiL6PtN8FIQt9MblqmLi0Hry4NrWjQQdwnQ8vwRb16RKjxLF5O4J6Xkv4pjeAsVJLJi5qpiLFz2uQn8m4PiQI6fY0lyo3ag2EXAYUaJsZRM92pcGWTEJYzWo55JwSzmHwxnaG9f3qp06IFz_xQ3qVm7g05iNDDYdOs-t1Mxz4fIrQ3brYfbFg80Xv_OhGvPGI4Ntm2f7VqEgGlTlRRuXl9-6b1-oictlekbATkIxojPZfB-ZbPCBcHViKJ9Mw0rD8bJbDCdl-I_yXeuNfAjLrmpjF7MuorKoJ7dK08otDzkebOIJP7qQ3BbyQd0uG7BMwwAh5BJwytmkcuVbw"}}, "payload": "eyJpZGVudGlmaWVyIjogeyJ0eXBlIjogImRucyIsICJ2YWx1ZSI6ICJmb28uY29tIn19", "signature": "XMJxL7idrIsh2ieJlElc7H8b57S6gsBDpC84DkL3FvDf5Quhb0wQRdsqWAmEnEXC8gF3TIEzGI4W2nTInylU2ca2H_rcJhhpTMObKmaZ1rX0Hqx8QFiDVoeu7XNVGQA81RV_KNlo0ej4YiusRvJr7VRK2uFB9Wn7kM6KFj3la_-kEoYTAmaRBcryzzcPlXLbKa5aeUtZT08eJ6fi_7f6J3WuseWpnyjiDv1wJt_HftsLJ00ix3EEygkuJJtRCbf9clAuuJfRTPpdDc42TuNF3wrlFlItSqwFMn-Pw2X4jMJGI2kGf_tmVaTVSL5Wfru3ZWj-LnXn3MAbA89aP1dr7A"}
DEBUG:root:Received response <Response [201]>: {"identifier":{"type":"dns","value":"foo.com"},"key":{"e":"AQAB","kty":"RSA","n":"rkxqHTiL6PtN8FIQt9MblqmLi0Hry4NrWjQQdwnQ8vwRb16RKjxLF5O4J6Xkv4pjeAsVJLJi5qpiLFz2uQn8m4PiQI6fY0lyo3ag2EXAYUaJsZRM92pcGWTEJYzWo55JwSzmHwxnaG9f3qp06IFz_xQ3qVm7g05iNDDYdOs-t1Mxz4fIrQ3brYfbFg80Xv_OhGvPGI4Ntm2f7VqEgGlTlRRuXl9-6b1-oictlekbATkIxojPZfB-ZbPCBcHViKJ9Mw0rD8bJbDCdl-I_yXeuNfAjLrmpjF7MuorKoJ7dK08otDzkebOIJP7qQ3BbyQd0uG7BMwwAh5BJwytmkcuVbw"},"status":"pending","expires":"0001-01-01T00:00:00Z","challenges":[{"type":"simpleHttps","status":"pending","uri":"https://www.letsencrypt-demo.org/acme/authz/5QAI1_s1ZU71HpghUM0RATsaRrZAQpuT4yMxTHXfKDA?challenge=0","token":"mNJS7oiNFH2GfVAsPc9Nr763Xld1PAZLmQNe0dhkSeQ"},{"type":"dvsni","status":"pending","uri":"https://www.letsencrypt-demo.org/acme/authz/5QAI1_s1ZU71HpghUM0RATsaRrZAQpuT4yMxTHXfKDA?challenge=1","r":"mxgVtg9L7imjzQOGTjCbziygn388rZAtFZXWrjdzCn0","nonce":"f7ca5861765fb80b03415942139383da"}],"combinations":[[0],[1]]}
INFO:root:Performing the following challenges:
INFO:root:  DVSNI challenge for foo.com.
I/O possible
(venv)root@le:~/lets-encrypt-preview# echo $?
157
(venv)root@le:~/lets-encrypt-preview# ps auxxww | grep letse
root     15423  0.0  7.6 121884 38696 pts/1    S    14:45   0:00 /root/lets-encrypt-preview/venv/bin/python2 /root/lets-encrypt-preview/venv/bin/letsencrypt -vvvv -ted foo.com -m admin@foo.com auth
```

**Comment by kuba** [comment]
Ah, that was a run for `letsencrypt -vvvv -ted foo.com -m admin@foo.com auth`, standalone authenticator.

**Comment by pde** [comment]
That sounds like a result of this [SIGIO from the standalone child to its parent](https://github.com/letsencrypt/lets-encrypt-preview/blob/master/letsencrypt/plugins/standalone/authenticator.py#L221) ("I/O possible" is the string description of the SIGIO signal).  But the fact that it's crashing is a bit odd, because the signal should be caught and handled [here](https://github.com/letsencrypt/lets-encrypt-preview/blob/master/letsencrypt/plugins/standalone/authenticator.py#L155).

@schoen is this a race condition, or something else?

**Comment by schoen** [comment]
@pde it's a race condition: the parent's first action is to set the signal handler, while the child signals the parent immediately after binding a port, which could nonetheless take a negligible amount of time.

I guess the correct solution would be to have the original process set the signal handler before forking, and then the child can revert the signal handler (which isn't applicable to it). There's no obvious way for the child to check whether or not the parent is ready to receive the signal, unless we want to start using other IPC primitives.

**Comment by schoen** [comment]
I've attempted to fix this in the branch `fix_standalone_signal_race`. Could you please test it?

**Comment by kuba** [comment]
@schoen it seems to work, you can send a PR :)
