### ISSUE TITLE
Missing doc for --checkpoints rollback flag

### ISSUE THREAD

**Issue by diracdeltas** [letsencrypt/lets-encrypt-preview#406]
12:17:55 PM - yan_eff: hey, is there still a way to rollback N checkpoints in the letsencrypt client?
12:22:50 PM - jdkasten: Hi Yan, yes sudo letsencrypt rollback --checkpoints N
12:25:25 PM - jdkasten: some work still needs to be done to make it intuitive... basically checkpoints is specific to the subcommand rollback
12:26:48 PM - jdkasten: so the option currently must come after the verb

**Comment by kuba** [comment]
```
$ letsencrypt rollback --help
usage: letsencrypt rollback [-h] [--checkpoints N]

Rollback.

optional arguments:
  -h, --help       show this help message and exit
  --checkpoints N  Revert configuration N number of checkpoints.
```

**Comment by diracdeltas** [comment]
Ah, didn't realize you could run --help on subcommands
