### ISSUE TITLE
Renewer directory command line flag

### ISSUE THREAD

**Issue by jsha** [letsencrypt/lets-encrypt-preview#436]
The renewer should take the directory to store data in as a command line flag.

This is important for integration testing.

**Comment by schoen** [comment]
Included in #429.

**Comment by schoen** [comment]
@jsha: would it be possible in the meantime to make an `/etc/letsencrypt/renewer.conf` that sets the directory? (Currently I *do* parse the directory out of that file, but not from the command line.) Or could the integration testing not readily write that file?

**Comment by schoen** [comment]
Relatedly, @kuba proposed (in the renewer PR, #404):

> The above directories should depend on IConfig.config_dir and IConfig.work_dir as supplied by the user. letsencrypt --config-dir /tmp/le/config --work /tmp/le/work will break the renewer. Hence the renewer script should symmetrically accept letsencrypt-renewer --config-dir /tmp/le/config --work-dir /tmp/le/work. Implementation is rather straightforward as it amounts to just a bit of copy&paste from cli.py and configuration.Namespace.
