### ISSUE TITLE
Many certificates for many websites on the same server?

### ISSUE THREAD

**Issue by kajmagnus** [letsencrypt/lets-encrypt-preview#454]
Hi dear Let's Encrypt,

Will you support installing certificates for many websites on one single server? For example, a certificate for `www.example.com`, another one for `another.site.com`, and a third certificate for `even-more.websites.org`? On one single IP address.

And renewing and revoking certs for individual websites? (For example, revoking for only `www.example.com` but for no other site)

If you will support wildcard certs, will the above work in combination with a wildcard cert for say `*.wildcard-example.org`?

Best regards, KajMagnus

(P.S. I did get the impression that you will indeed support many sites on the same server, since the command line looks like: `lets-encrypt example.com`)

**Comment by schoen** [comment]
You can get several different certificates for sites that are hosted on the same IP address, or you can get a single SAN cert (subjectAltName) cert that covers all of them.  Then the cert will be compatible with clients that don't use SNI.

https://en.wikipedia.org/wiki/SubjectAltName
https://en.wikipedia.org/wiki/Server_Name_Indication

If you have an SNI cert, you can renew it with a single name removed, while if you have individual certs that happen to be used on the same machine, you can renew or revoke them independently of one another.  (I'm about to work on some code for #411, which addresses the question of what the client default behavior is in each of these situation.)

We don't currently have a plan to support wildcard certs.

**Comment by kajmagnus** [comment]
Thank you this was very helpful.
