### ISSUE TITLE
Can I secure a sub domain even if I don't own the main domain?

### ISSUE THREAD

**Issue by kajmagnus** [letsencrypt/lets-encrypt-preview#455]
Hi,

Can I secure a domain like `forum.example.com` even though I don't own `example.com`? Assuming the people at `example.com` has configured their DNS servers to map `forum.example.com` to my server, where I host their forum.

I noticed that sub domains are supported (https://github.com/letsencrypt/lets-encrypt-preview/issues/355) but I'm not sure if I need to own the main domain.

Best regards, KajMagnus

**Comment by schoen** [comment]
Yes, the proof-of-control validation is done to the individual identifier you specify, not to a parent identifier.
