### ISSUE TITLE
When we will be able to use letsencrypt?

### ISSUE THREAD

**Issue by dashohoxha** [letsencrypt/lets-encrypt-preview#460]
The SSL certificate for one of my domains is expiring in 2-3 weeks. Should I renew it, or I will be able to get a new certificate from letsencrypt before that time?

**Comment by pde** [comment]
Sorry, we can't discuss precise timing for the public launch.  So to be on the safe side, you should renew your certificate with your existing CA.

**Comment by dashohoxha** [comment]
OK, this is a safe answer.

But I am also ready to do some manual configuration work, pre-alpha testing, etc. as long as **letsencrypt** can issue a valid certificate for me. I don't expect everything to work smoothly and perfectly right now.

So, is **letsencrypt** ready to issue a free valid certificate for me?
First let's make it work, and then let's make it better/smoother/perferct/whatever.
