### ISSUE TITLE
Separate --test-mode and --no-verify-ssl

### ISSUE THREAD

**Issue by kuba** [letsencrypt/lets-encrypt-preview#462]
This is necessary for integration testing, where self-signed certs and `443` port is used. `--test-mode` currently implies that `StandaloneAuthenticator` on `5001` port.

cc @jcjones

**Comment by schoen** [comment]
Is there a way to leave `--no-verify-ssl` out of client versions that will reach end-users?  I'm nervous about having it in there for non-testing environments.
