### ISSUE TITLE
Unable to register an account with ACME server

### ISSUE THREAD

**Issue by 3vILVIrUs** [letsencrypt/lets-encrypt-preview#478]
Hello,
I am testing the client against another ca server (local boulder instance using docker), and I get the error message "Unable to register an account with ACME server" right after choosing the authenticator. However, the client does not communicate with the ca server (or any other server) while running.
Using it with the default server works. The vm, which im running the client in, can communicate with the ca server aswell as the internet.

**Comment by kuba** [comment]
Please paste the exact command and the output, I suggest using `-vvvvv --text`. Thanks.

Did you use `--server http://localhost:4000 --no-verify-ssl`? If you're using boulder test mode, you should also set `--dvsni-port 5001`.

**Comment by kuba** [comment]
ups, meant `--server http://localhost:4000/acme/new-reg`

**Comment by 3vILVIrUs** [comment]
Using the url path the client did communicate with the server, which resulted in an internal server error (missing tables; forgot the sql config): http://pastebin.com/38NmQhRF
After fixing this, I get Connection refused: http://pastebin.com/U41JjuVC
On the server side, I get this output: http://pastebin.com/AVMidGU0
The --no-verify-ssl argument did not exist; I only found --test-mode in the help. Using it did not change the result.

**Comment by kuba** [comment]
`--server http://172.17.42.1:4000/acme/new-re` vs `DEBUG:root:Sending POST data to http://localhost:4000/acme/new-authz` . You should update Boulder config from `"baseURL": "http://localhost:4000",` to  `"baseURL": "http://172.17.42.1:4000",`.

Please also update client to the latest `master` and run with `--dvsni-port 5001` (corresponds to Boulder's `"TestMode": true,`) and `--no-verify-ssl`.

**Comment by kuba** [comment]
Ah, forgot to mention that custom `--dvsni-port` works with the standalone authenticator only, it will not work with Apache or nginx. see #479.

**Comment by 3vILVIrUs** [comment]
Thank you, that solved the communication problem.
Now I get another, probably unrelated issue. It fails the authorization procedure: http://pastebin.com/ejctFZVd
The boulder-ca and the letsencrypt-vm use a local nameserver where test.de are set to the ip of my vm. I guess there is some kind of other configuration that needs to be in place to fully authorize the domain (I don't own test.de, I just use it to test the ca locally)?
Also I am experiencing https://github.com/letsencrypt/lets-encrypt-preview/issues/365 using the standalone authenticator.

**Comment by kuba** [comment]
`letsencrypt.errors.AuthorizationError: Failed Authorization procedure for test.de` usually happens when Boulder cannot access client's port (in this case `5001`). Make sure that boulder-ca resolves `test.de` to letsencrypt-vm IP and that the firewall is open.

**Comment by 3vILVIrUs** [comment]
I checked again that boulder resolves test.de right and that it can access port 5001 (it can access all ports). The apache2 authorization does fail aswell.

**Comment by 3vILVIrUs** [comment]
I captured the authorization procedure with wireshark and there is no communication on port 5001.
Here is the server log output: http://pastebin.com/B6i4akhx

**Comment by jdkasten** [comment]
The Apache plugin does not support local testing currently. #479

**Comment by 3vILVIrUs** [comment]
I am still not able to authenticate. I confirmed that boulder resolves `test.de` correctly to the vm and that boulder can access open ports (specifically 5001, 80 and 443) on that vm.
I am using standalone authenticator.

**Comment by kuba** [comment]
Excerpt from http://pastebin.com/ejctFZVd:
```
{"type":"dvsni","status":"invalid","uri":"http://172.17.42.1:4000/acme/authz/zSTWaxb3yc2iXBcxsWZKm0qG_SIZpsNGV-sSK5yqcug?challenge=1","r":"tp3zbxKVq3A9QHb2TfIEfnuiLKyMVO9kaXYopyApB-g","s":"iEy-j-MB_wi-KOl-EiQiFrrio22gFBUsbViv70A-y0c","nonce":"07432605984782bc3ebc8c13be7f06fe"},"RequestTime":"2015-06-03T14:13:24.393479308Z","ResponseTime":"0001-01-01T00:00:00Z","Error":"dial tcp \u003cnil\u003e-\u003e127.0.0.1:5001: getsockopt: connection refused"}
```

It seems that Boulder tries to connect to `127.0.0.1:5001` rather than IP of your letsencrypt-vm instance. Indeed, `localhost` is hardcoded, c.f. https://github.com/letsencrypt/boulder/blob/d6220b21783188a9534a5e9cfaca444b6544ee26/va/validation-authority.go#L62-65. Please close the issue here, and continue at freshly opened https://github.com/letsencrypt/boulder/issues/331.
