### ISSUE TITLE
Is there an alternative way of proofing a webserver's property?

### ISSUE THREAD

**Issue by martensms** [letsencrypt/lets-encrypt-preview#500]
Hey guys,

I wanted to try out the lets-encrypt-preview, but it seems to currently support only apache and nginx.

Is there a way to manually configure the proofs etc.?

Like "you have to put this proof file at /blabla12836.html on example.org. Then execute this wizard again."

For my infrastructure, I'm using mostly nodejs / iojs static builds. That's why my paths of servers and apps are completely different compared to usual apache paths.

I would also love to add support for nodejs to this project, but I'm kind of stuck in between the whole process. Are there any documentation on how to create your own "platform adapter"?

Also, is there a plan to help this tool support authentication of onion domains within the TOR project or say, hyperboria? I think this project has huge potential bringing meshnets to a whole new level.

**Comment by kuba** [comment]
I have implemented the manual authenticator plugin in #502. Would you like to test? :)

In general, if you want to work on specific nodejs support, the right way to do it, is to create another Authenticator plugin. General info can be found in `interfaces.py`. See `ManualAuthenticator`, `StandaloneAuthenticator`, `ApacheConfigurator` and `NginxConfigurator` for examples.
