### ISSUE TITLE
[Question] Third level domain certificate?

### ISSUE THREAD

**Issue by pparent76** [letsencrypt/lets-encrypt-preview#522]
Hi,

Thanks for your initiative it looks amathing!

Just a quick question, I was wondering if it will be possible to get a certificate for a particular subdomain?

For example mysubdomain.mydnsprovider.org

(With different SSL key for different subdomains)

I.e Will it be possible to do 
"lets-encrypt my.example.com"

Actually I am author of Own-Mailbox (see Own-Mailbox.com), I will offer free subdomain to users, they will all have a different SSL key, and I am looking for a way to let them have a free SSL certificate recognized by the browser.

Thanks in advence,
Keep up the great job!

Pierre.

**Comment by kajmagnus** [comment]
I think you can. See https://github.com/letsencrypt/lets-encrypt-preview/issues/355 and https://github.com/letsencrypt/lets-encrypt-preview/issues/455.

**Comment by pparent76** [comment]
Ok Thanks!
