### ISSUE TITLE
running the script should not require root.

### ISSUE THREAD

**Issue by dnozay** [letsencrypt/lets-encrypt-preview#83]
I think it is unnecessary for the script to require `root` for running the script.

*  I could be preparing everything on a different machine from where the certs will actually be used (think puppet, chef, ansible ...etc)
* I could be running the script where the configuration files actually are, e.g. on the master where the configuration will be kept or a git clone, or even some workspace that I gets `rsync`'d to the target machine.

Think of the difference between `make` and `make install`, usually I would prefer to do `make install DESTDIR=/tmp/inspectme` rather than blindly run a script as `root`.

**Comment by jdkasten** [comment]
This conversation has transitioned to other forums.
